# Generated by Django 2.1.7 on 2020-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='id',
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
